name: todos_repository
description: A repository that handles todo related requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  todos_api:
    path: ../todos_api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
